using EXILED;
using System;
using System.Collections.Generic;

namespace MultiPlugin22
{
	internal static class Configs
	{
		public static bool isEnabled;
		public static string databaseName;
		public static string generalChatColor;
		public static string privateMessageColor;
		public static int maxMessageLength;
		public static bool censorBadWords;
		public static char censorBadWordsChar;
		public static List<string> badWords;
		public static bool saveChatToDatabase;
		public static bool canSpectatorSendMessagesToAlive;
		public static bool showChatMutedBroadcast;
		public static ushort chatMutedBroadcastDuration;
		public static string chatMutedBroadcast;
		public static bool showPrivateMessageNotificationBroadcast;
		public static uint privateMessageNotificationBroadcastDuration;
		public static string privateMessageNotificationBroadcast;
		public static bool isSlowModeEnabled;
		public static TimeSpan slowModeCooldown;
		public static string min;
		public static string sec;
		public static string reason;
		public static string msg;
		public static string command;
		public static string commandlist;
		public static string team;
		public static string publict;
		public static string privatet;
		public static string l1;
		public static string l2;
		public static string l3;
		public static string l4;
		public static string l5;
		public static string l6;
		public static string l7;
		public static string l8;
		public static string l9;
		public static string l10;
		public static string l11;
		public static string l12;
		public static string l13;
		public static string l14;
		public static string l15;
		public static string l16;
		public static string l17;
		public static string l18;
		public static string l19;
		public static string l20;
		public static string l21;
		public static string l22;
		public static string l23;
		public static string l24;
		public static string l25;
		public static string l26;
		public static string l27;
		public static string l28;
		public static string l29;
		public static string l30;
		public static string l31;
		public static string l32;
		public static string l33;

		public static void Reload()
		{
			isEnabled = Plugin.Config.GetBool("mp_enabled", true);
			databaseName = Plugin.Config.GetString("mp_database_name", "MultiPluginChat");
			generalChatColor = Plugin.Config.GetString("mp_general_chat_color", "cyan");
			privateMessageColor = Plugin.Config.GetString("mp_private_message_color", "magenta");
			maxMessageLength = Plugin.Config.GetInt("mp_max_message_length", 100);
			censorBadWords = Plugin.Config.GetBool("mp_censor_bad_words");
			censorBadWordsChar = Plugin.Config.GetChar("mp_censor_bad_words_char", '*');
			badWords = Plugin.Config.GetStringList("mp_bad_words");
			saveChatToDatabase = Plugin.Config.GetBool("mp_save_chat_to_database", true);
			canSpectatorSendMessagesToAlive = Plugin.Config.GetBool("mp_can_spectator_send_messages_to_alive");
			showChatMutedBroadcast = Plugin.Config.GetBool("mp_show_chat_muted_broadcast", true);
			chatMutedBroadcastDuration = Plugin.Config.GetUShort("mp_chat_muted_broadcast_duration", 10);
			chatMutedBroadcast = Plugin.Config.GetString("mp_chat_muted_broadcast", "<color=red>Вы были отключены от чата на {0} минут, причина: {1}</color>");
			showPrivateMessageNotificationBroadcast = Plugin.Config.GetBool("mp_show_private_message_notification_broadcast", true);
			privateMessageNotificationBroadcastDuration = Plugin.Config.GetUInt("mp_private_message_notification_broadcast_duration", 6);
			privateMessageNotificationBroadcast = Plugin.Config.GetString("mp_private_message_notification_broadcast", "Вы получили личное сообщение!");
			isSlowModeEnabled = Plugin.Config.GetBool("mp_is_slow_mode_enabled", true);
			slowModeCooldown = new TimeSpan(0, 0, 0, 0, (int)(Plugin.Config.GetFloat("mp_slow_mode_interval", 1f) * 1000));
			min = Plugin.Config.GetString("mp_chat_min", "minutes");
			sec = Plugin.Config.GetString("mp_chat_sec", "sec");
			reason = Plugin.Config.GetString("mp_chat_reason", "reason");
			msg = Plugin.Config.GetString("mp_chat_msg", "message");
			command = Plugin.Config.GetString("mp_chat_com", "Command");
			commandlist = Plugin.Config.GetString("mp_chat_com_list", "СПИСОК КОМАНД");
			team = Plugin.Config.GetString("mp_chat_team", "TEAM");
			publict = Plugin.Config.GetString("mp_chat_public", "PUBLIC");
			privatet = Plugin.Config.GetString("mp_chat_private", "PRIVATE");
			l1 = Plugin.Config.GetString("mp_chat_lang_1", "Вы не можете отправлять сообщения от сервера!");
			l2 = Plugin.Config.GetString("mp_chat_lang_2", "Произошла ошибка при выполнении команды!");
			l3 = Plugin.Config.GetString("mp_chat_lang_3", "<color=lime>На этом сервере существует чат</color>\n<color=red>.help</color>");
			l4 = Plugin.Config.GetString("mp_chat_lang_4", "Добро пожаловать в чат!");
			l5 = Plugin.Config.GetString("mp_chat_lang_5", "%player% покинул чат!");
			l6 = Plugin.Config.GetString("mp_chat_lang_6", "Включить игроку чат");
			l7 = Plugin.Config.GetString("mp_chat_lang_7", "У вас недостаточно прав для запуска этой команды!");
			l8 = Plugin.Config.GetString("mp_chat_lang_8", "Вы должны предоставить один параметр!");
			l9 = Plugin.Config.GetString("mp_chat_lang_9", "%player% не найден!");
			l10 = Plugin.Config.GetString("mp_chat_lang_10", "%player% не замьючен!");
			l11 = Plugin.Config.GetString("mp_chat_lang_11", "<size=25><color=lime>Вы были размьючены в чате!</color></size>");
			l12 = Plugin.Config.GetString("mp_chat_lang_12", "%player% был размьючен в чате");
			l13 = Plugin.Config.GetString("mp_chat_lang_13", "Отключить звук игрока из чата.");
			l14 = Plugin.Config.GetString("mp_chat_lang_14", "Вы должны предоставить два параметра!");
			l15 = Plugin.Config.GetString("mp_chat_lang_15", "%time% недопустимая продолжительность!");
			l16 = Plugin.Config.GetString("mp_chat_lang_16", "Причина не может быть пустой!");
			l17 = Plugin.Config.GetString("mp_chat_lang_17", "%player% уже отключен!");
			l18 = Plugin.Config.GetString("mp_chat_lang_18", "<size=25><color=red>Вы были отключены от чата на %duration%! Причина: %reason%</color></size>");
			l19 = Plugin.Config.GetString("mp_chat_lang_19", "%player% был отключен в чате на %duration%, причина: %reason%");
			l20 = Plugin.Config.GetString("mp_chat_lang_20", "Отправляет сообщение в чат вашей команде.");
			l21 = Plugin.Config.GetString("mp_chat_lang_21", "Нет доступных игроков для общения!");
			l22 = Plugin.Config.GetString("mp_chat_lang_22", "Отправляет сообщение всем на сервере.");
			l23 = Plugin.Config.GetString("mp_chat_lang_23", "Отправляет личное сообщение в чат игроку.");
			l24 = Plugin.Config.GetString("mp_chat_lang_24", "Вы не можете отправить сообщение себе!");
			l25 = Plugin.Config.GetString("mp_chat_lang_25", "Вы не можете отправлять сообщения живым игрокам!");
			l26 = Plugin.Config.GetString("mp_chat_lang_26", "Отправляет список команд или описание отдельной команды.");
			l27 = Plugin.Config.GetString("mp_chat_lang_27", "Нет команд для отправки!");
			l28 = Plugin.Config.GetString("mp_chat_lang_28", "Команда %command% не найдена!");
			l29 = Plugin.Config.GetString("mp_chat_lang_29", "Слишком много аргументов!");
			l30 = Plugin.Config.GetString("mp_chat_lang_30", "Сообщение не может быть пустым!");
			l31 = Plugin.Config.GetString("mp_chat_lang_31", "Вы отправляете сообщения слишком быстро!");
			l32 = Plugin.Config.GetString("mp_chat_lang_32", "Сообщение слишком длинное! Максимальная длина: %length%");
			l33 = Plugin.Config.GetString("mp_chat_lang_33", "Вы замьючены!");
		}
	}
}
